name: 'slurm'
on: push
jobs:
  install:
    runs-on: ubuntu-21.04
    steps:
      - name: test0
        run: |
          sudo add-apt-repository universe
          sudo apt-get -y update
          sudo apt-get -y install slurm-wlm
  test-step:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: qualcosa
        run: |
          touch ~/github-actions
